### ISSUE TITLE
Interpreter builds modules twice

### ISSUE THREAD

**Issue by stevenmburns** [freechipsproject/firrtl-interpreter#86] opened 2017-06-08 01:03 UTC
This simple example shows that a module is built twice. (Not the case with VCS or Verilator.)

````
package twice

import org.scalatest.{ Matchers, FlatSpec}

import chisel3._
import chisel3.iotesters._

class RunsTwiceBug extends Module {
  println( s"Building RunsTwiceBug...")
  val io = IO(new Bundle {
    val a = Input(Bool())
    val o = Output(Bool())
  })
  io.o := io.a
}

class Tester(c:RunsTwiceBug) extends PeekPokeTester(c) {
  poke( c.io.a, BigInt(0))
  expect( c.io.o, BigInt(0))
}

class FirrtlTest extends FlatSpec with Matchers {
  behavior of "RunsTwiceBug"
  it should "work" in {
    chisel3.iotesters.Driver( () => new RunsTwiceBug, "firrtl") { c =>
      new Tester( c)
    } should be ( true)
  }
}
````
Here is the log:
````
dlxc1573> sbt 'testOnly twice.*'
[info] Loading global plugins from /nfs/site/disks/scl.work.46/ppt/users/smburns/chisel/.sbt/0.13/plugins
[info] Set current project to imperative (in build file:/nfs/site/disks/scl.work.59/ppt/smburns/tdd_using_chisel-testing_flows/imperative/)
[info] Compiling 1 Scala source to /nfs/site/disks/scl.work.59/ppt/smburns/tdd_using_chisel-testing_flows/imperative/target/scala-2.11/test-classes...
[info] FirrtlTest:
[info] RunsTwiceBug
[info] [0.002] Elaborating design...
Building RunsTwiceBug...
[info] [0.075] Done elaborating.
[info] [0.000] Elaborating design...
Building RunsTwiceBug...
[info] [0.004] Done elaborating.
End of dependency graph
Circuit state created
[info] [0.002] SEED 1496883454063
test RunsTwiceBug Success: 1 tests passed in 5 cycles taking 0.014406 seconds
[info] [0.004] RAN 0 CYCLES PASSED
[info] - should work
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 1 second, 41 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
[success] Total time: 9 s, completed Jun 7, 2017 5:57:34 PM
````
It also seems that firrtl transformations ("-fct" options) are run the first time through, but are not run the second time (and the second run is being used by the interpreter.)

**Comment by chick** [comment] 2017-06-08 17:46
Good catch, a function call was regenerating the firrtl that had been already generated two lines above.  Fixed in [#chisel-testers/pr154](/ucb-bar/chisel-testers/pull/154)

**Comment by stevenmburns** [comment] 2017-06-08 17:53
Chick, here is a test for whether the transforms are working right.

````
package twice

import org.scalatest.{ Matchers, FlatSpec}

import chisel3._
import chisel3.iotesters._

import firrtl.{Transform, LowForm, CircuitState, WRef, PortKind, MALE}
import firrtl.ir.{Circuit, DefModule, Statement, Expression, UIntLiteral, IntWidth, Block, Print, NoInfo, StringLit, ClockType}
import firrtl.Mappers._

class AddPrintf extends Transform {
  def inputForm = LowForm
  def outputForm = LowForm
  def execute( state : CircuitState) : CircuitState = {
    println( s"Running FIRRTL transform AddPrintf...")

    def onStmt( m : DefModule)( s : Statement ) : Statement = {

      s match {
        case Block( lst) =>
          val prnt =
            Print(
              NoInfo,
              StringLit( s"Running module ${m.name}\n".getBytes),
              Seq[Expression](),
              WRef( "clock", ClockType, PortKind, MALE),
              UIntLiteral(1,IntWidth(1))
            )
          Block( lst ++ List( prnt))
      }

    }

    val mods = state.circuit.modules map { case m : DefModule =>
      m map onStmt(m)
    }

    state.copy( circuit = state.circuit.copy( modules = mods))
  }
}

class RunsTwiceBug extends Module {
  println( s"Building RunsTwiceBug...")
  val io = IO(new Bundle)
}

class Tester(c:RunsTwiceBug) extends PeekPokeTester(c) {
  step(1)
}

class FirrtlTest extends FlatSpec with Matchers {
  behavior of "RunsTwiceBug"
  it should "work" in {
    chisel3.iotesters.Driver.execute( Array( "-fct", "twice.AddPrintf", "--backend-name", "firrtl"), () => new RunsTwiceBug) { c =>
      new Tester( c)
    } should be ( true)
  }
}

class VerilatorTest extends FlatSpec with Matchers {
  behavior of "RunsTwiceBug"
  it should "work" in {
    chisel3.iotesters.Driver.execute( Array( "-fct", "twice.AddPrintf", "--backend-name", "verilator"), () => new RunsTwiceBug) { c =>
      new Tester( c)
    } should be ( true)
  }
}
````
Before your fix, the transform got into the Verilator simulation but not into the FIRRTL one.

**Comment by chick** [comment] 2017-06-08 18:11
It seems to be getting into the interpreter situation if I am reading this output right

test-only examples.FirrtlTest
[info] [0.002] Elaborating design...
Building RunsTwiceBug...
[info] [0.094] Done elaborating.
**Running FIRRTL transform AddPrintf...**
Total FIRRTL Compile Time: 282.5 ms
Total FIRRTL Compile Time: 12.8 ms
End of dependency graph
Circuit state created
[info] [0.004] SEED 1496945359775

**Comment by stevenmburns** [comment] 2017-06-08 19:07
The verilator test also prints out "[info] [0.023] Running module RunsTwiceBug" at runtime.
That is what the transform introduced. Do you see that?

````
sim start on dlxc1573 at Thu Jun  8 12:05:31 2017
inChannelName: 00014754.in
outChannelName: 00014754.out
cmdChannelName: 00014754.cmd
STARTING test_run_dir/twice.VerilatorTest598016335/VRunsTwiceBug
[info] [0.000] SEED 1496948730259
[info] [0.023] Running module RunsTwiceBug
Enabling waves..
Exit Code: 0
[info] [0.035] RAN 1 CYCLES PASSED
[info] - should work
[info] ScalaCheck
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] ScalaTest
[info] Run completed in 5 seconds, 395 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 8 s, completed Jun 8, 2017 12:05:32 PM
````

**Comment by chick** [comment] 2017-06-08 20:41
@stevenmburns the problem is not fixed, the transform is being run but the firrtl generated is somehow misplaced on the way to the interpreter, digging in now

**Comment by chick** [comment] 2017-06-08 21:55
@stevenmburns I think it is fixed now, found the misplaced firrtl and passed it down.  The output here is slightly different. 
Circuit state created
Running module RunsTwiceBug
Running module RunsTwiceBug
Running module RunsTwiceBug
Running module RunsTwiceBug
Running module RunsTwiceBug
[info] [0.002] SEED 1496958781721
Running module RunsTwiceBug

The interpreter seems to have several warm-up cycles, that could be fixed I suppose but I think it would be a separate issue.
I'm going to merge the PR on chisel-testers

**Comment by stevenmburns** [comment] 2017-06-08 22:26
Great. This behavior is not necessarily a bug, but probably me not guarding the print statement properly with !reset.

**Closed** 2017-09-18 23:41 UTC
